### post profile
POST http://localhost:8080/api/profile
Content-Type: application/json

{
  "name": "Farrux",
  "surname": "Boqiyev",
  "email": "fboqiev1065@gmail.com",
  "phone": "+998901234567",
  "password": "1065"
}
