### Registration using Email
POST localhost:8080/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Farruxbek",
  "surname": "Baqiyev",
  "username": "fboqiyev1065@mail.ru",
  "password": "1065"
}

### Email registration confirm
GET http://localhost:8080/api/v1/auth/registration/email/verification/fboqiyev1065@mail.ru/98785



### Login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "fboqiyev1065@mail.ru",
  "password": "1065"
}

